### PR TITLE
Untyped properties

### PR DESCRIPTION
**Pull request by delixfe**
Hi @kuanysh-nabiyev,

I was able to identify the type of some properties which are still `object`.

### CODE REVIEW

**Comment by kuanysh-nabiyev** [comment]
thanks for pull requst
I will increment nuget package version

**Comment by delixfe** [comment]
Hi @kuanysh-nabiyev,

thanks for merging :). It looks like the build of the NuGet package version 1.0.2 was stale as it neither contains the changes of this PR nor from #2.

**Comment by kuanysh-nabiyev** [comment]
Hi @delixfe ,

sorry for that. I have incremented the package version. It has not been indexed yet, but it should appear soon

**Comment by delixfe** [comment]
Hey @kuanysh-nabiyev,

no issues. Thanks for the super fast response and solution....

**Pull request merged**
